name: Deploy VitePress to Vercel

on:
  push:
    branches: [release/1.2]
    paths:
      - "docs/**"
    pull_request:
      branches: [release/1.2]

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs # å°†å·¥ä½œç›®å½•è®¾ä¸º docs å­ç›®å½•
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          version: "^8.0"

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: pnpm run docs:build

      - name: Vercel Deployment
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          working-directory: .vitepress/dist
